### ISSUE TITLE
[BUG] since v4.0.0: mem_cache_mutex' does not have a constant initializer

### ISSUE THREAD

**Issue by brechtsanders** [bluescarni/heyoka#403]
**Issue**
Since version 4.0.0 heyoka  no longer builds with MinGW-w64 / GCC 13.2.0.
The build fails with the following error:
```raw
src/llvm_state_mem_cache.cpp:51:29: error: call to non-'constexpr' function 'std::mutex::mutex()'
```

The complete output when building 4.0.1 is:
```raw
[117/142] Building CXX object CMakeFil...a.dir/src/llvm_state_mem_cache.cpp.obj
FAILED: CMakeFiles/heyoka.dir/src/llvm_state_mem_cache.cpp.obj
D:\Prog\winlibs-gcc13.2.0-posix-msvcrt-11.0.1\mingw64\bin\c++.exe -DBOOST_ALLOW_DEPRECATED_HEADERS -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_CONTAINER_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SERIALIZATION_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_USE_DLL -DHEYOKA_BUILD_LIBRARY -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -D_FILE_OFFSET_BITS="64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" -IR:/winlibs-gcc13.2.0-posix-msvcrt-11.0.1_64/heyoka-4.0.1/include -IR:/winlibs-gcc13.2.0-posix-msvcrt-11.0.1_64/heyoka-4.0.1/build_static/include -isystem D:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/custombuilt64/share/llvm/include -isystem D:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/custombuilt64/include -O3 -DNDEBUG -std=c++20 -flto=auto -fno-fat-lto-objects -fdiagnostics-color=auto -ftemplate-depth=1024
-fdiagnostics-show-template-tree -Wno-attributes -MD -MT CMakeFiles/heyoka.dir/src/llvm_state_mem_cache.cpp.obj -MF CMakeFiles\heyoka.dir\src\llvm_state_mem_cache.cpp.obj.d -o CMakeFiles/heyoka.dir/src/llvm_state_mem_cache.cpp.obj -c R:/winlibs-gcc13.2.0-posix-msvcrt-11.0.1_64/heyoka-4.0.1/src/llvm_state_mem_cache.cpp
R:/winlibs-gcc13.2.0-posix-msvcrt-11.0.1_64/heyoka-4.0.1/src/llvm_state_mem_cache.cpp:51:29: error: 'constinit' variable 'heyoka::v27::detail::{anonymous}::mem_cache_mutex' does not have a constant initializer
   51 | HEYOKA_CONSTINIT std::mutex mem_cache_mutex;
      |                             ^~~~~~~~~~~~~~~
R:/winlibs-gcc13.2.0-posix-msvcrt-11.0.1_64/heyoka-4.0.1/src/llvm_state_mem_cache.cpp:51:29: error: call to non-'constexpr' function 'std::mutex::mutex()'
In file included from D:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/mingw64/include/c++/13.2.0/mutex:45,
                 from R:/winlibs-gcc13.2.0-posix-msvcrt-11.0.1_64/heyoka-4.0.1/src/llvm_state_mem_cache.cpp:15:
D:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/mingw64/include/c++/13.2.0/bits/std_mutex.h:104:5: note: 'std::mutex::mutex()' is not usable as a 'constexpr' function because:
  104 |     mutex() noexcept = default;
      |     ^~~~~
D:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/mingw64/include/c++/13.2.0/bits/std_mutex.h:71:5: note: defaulted constructor calls non-'constexpr' 'std::__mutex_base::__mutex_base()'
   71 |     __mutex_base() noexcept
      |     ^~~~~~~~~~~~
D:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/mingw64/include/c++/13.2.0/bits/std_mutex.h:71:5: note: 'std::__mutex_base::__mutex_base()' declared here
[140/142] Building CXX object CMakeFiles/heyoka.dir/src/step_callback.cpp.obj
ninja: build stopped: subcommand failed.
```

The CMake flags I used were:
```raw
-DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL=OFF -DHEYOKA_ENABLE_IPO:BOOL=ON -DHEYOKA_BUILD_STATIC_LIBRARY:BOOL=ON -DHEYOKA_ENABLE_IPO:BOOL=ON -DHEYOKA_WITH_MPPP:BOOL=ON -DHEYOKA_WITH_SLEEF:BOOL=ON -DLLVM_DIR:PATH=$MINGWPREFIX/share/llvm/lib/cmake/llvm -DHEYOKA_BUILD_TUTORIALS:BOOL=OFF -DHEYOKA_BUILD_BENCHMARKS:BOOL=OFF -DHEYOKA_BUILD_TESTS:BOOL=OFF 
```

**My environment**
 - OS: Windows 11
 - Shell: MSYS2 shelll
 - Build tools: GCC 13.2.0 from https://winlibs.com/
 - Version: 4.0.0 + 4.0.1

**Comment by bluescarni** [comment]
hi @brechtsanders and thanks for the report!

The constructor of ``std::mutex`` should be marked as ``constexpr`` since C++11:

https://en.cppreference.com/w/cpp/thread/mutex/mutex

So I am a bit surprised that it is not yet ``constexpr`` in MinGW GCC 13.

Nevertheless, the ``constinit`` bit is not really necessary and I think we can work around by avoiding constinit initialisation on MinGW specifically. I have opened a PR with the fix here #404. Could you test it out and tell me if if fixes compilation for you?

**Comment by brechtsanders** [comment]
I can confirm #404  builds with MinGW-w64 GCC 13.2.0

**Comment by bluescarni** [comment]
Fixed in heyoka 4.0.2.
